{"link": "http://techcrunch.com/topic/product/android/"}
{"link": "http://techcrunch.com/topic/product/dropbox-2/"}
{"link": "http://techcrunch.com/2014/07/01/blablacar-raises-a-massive-100-million-round-to-create-a-global-ride-sharing-network/"}
{"link": "http://techcrunch.com/2014/07/01/google-the-cube/"}
{"link": "http://techcrunch.com/2014/07/01/tinder-ceos-internal-memo-claims-harrassment-complaint-is-innacurate/"}
{"link": "http://techcrunch.com/2014/07/01/senators-call-on-obama-for-more-transparency-in-the-intelligence-community/"}
{"link": "http://techcrunch.com/2014/07/01/oculus-rift-dk2-shipping-date/"}
{"link": "http://techcrunch.com/2014/07/01/vevo-product-michael-cerda-leaves/"}
{"link": "http://techcrunch.com/2014/07/01/bring-on-the-blogging-robots/"}
{"link": "http://techcrunch.com/2014/07/01/makerskit-raises-1-5-million-in-seed-funding-to-launch-a-diy-empire/"}
{"link": "http://techcrunch.com/2014/07/01/with-political-failures-left-and-right-tech-needs-to-rethink-its-strategy/"}
{"link": "http://techcrunch.com/2014/07/01/dropbox-buys-e-commerce-ab-testing-service-predictive-edge-shuts-it-down/"}
{"link": "http://techcrunch.com/2014/07/01/clever-oculus-project-lets-you-live-your-life-in-third-person/"}
{"link": "http://techcrunch.com/2014/07/01/googles-smarty-pins-lets-you-test-your-geography-knowledge/"}
{"link": "http://techcrunch.com/2014/07/01/icloak-stik/"}
{"link": "http://techcrunch.com/2014/07/01/lawrence-lessigs-campaign-reform-push-comes-to-a-head-this-friday/"}
{"link": "http://techcrunch.com/2014/07/01/google-buys-songza/"}
{"link": "http://techcrunch.com/2014/07/01/ftc-accuses-t-mobile-of-allowing-shady-scams-to-sneak-onto-your-phone-bill/"}
{"link": "http://techcrunch.com/2014/07/01/mapr-gains-110-million-in-funding-led-by-google-capital/"}
{"link": "http://techcrunch.com/2014/07/01/online-education-startups-codecademy-general-assembly-others-band-together-against-net-neutrality/"}
{"link": "http://techcrunch.com/2014/07/01/facebook-starts-using-app-links-to-get-you-back-into-apps/"}
{"link": "http://techcrunch.com/2014/07/01/facebook-ad-receipts/"}
{"link": "http://techcrunch.com/2014/07/01/after-losing-in-the-supreme-court-aereo-turns-its-sights-to-congress/"}
{"link": "http://techcrunch.com/2014/07/01/72lux-launches-shoppable-giving-users-a-universal-wish-list-with-multiple-retailers/"}
{"link": "http://techcrunch.com/2014/07/01/whats-disrupt-sf-without-a-fireside-chat-between-marc-benioff-and-michael-arrington/"}
{"link": "http://techcrunch.com/2014/07/01/kudoso-is-a-router-that-rewards-your-kids-with-facebook-time-for-studying-doing-chores/"}
{"link": "http://techcrunch.com/2014/07/01/arista-networks-gopro-and-jd-com-spike-pumping-fresh-oxygen-into-the-tech-ipo-market/"}
{"link": "http://techcrunch.com/2014/07/01/dropbox-for-enterprise/"}
{"link": "http://techcrunch.com/2014/07/01/nightingale/"}
{"link": "http://techcrunch.com/2014/07/01/hp-shareholder-settlement-is-latest-chapter-in-autonomy-saga/"}
{"link": "http://techcrunch.com/2014/07/01/hinge-app/"}
{"link": "http://techcrunch.com/2014/07/01/partnered-raises-850k-in-fresh-seed-funding-to-pair-big-brands-with-startups/"}
{"link": "http://techcrunch.com/2014/07/01/simply-hired-funding/"}
{"link": "http://techcrunch.com/2014/07/01/startups-surge-in-south-america/"}
{"link": "http://techcrunch.com/2014/07/01/vine-update-introduces-loop-counts-so-you-know-how-great-you-are/"}
{"link": "http://techcrunch.com/2014/07/01/an-upper-limit-for-apps-new-data-suggests-consumers-only-use-around-two-dozen-apps-per-month/"}
{"link": "http://techcrunch.com/2014/07/01/amazon-launches-its-most-affordable-ec2-instances-yet-but-theres-a-caveat/"}
{"link": "http://techcrunch.com/2014/07/01/virtual-says-it-can-emulate-ios-or-android-devices-in-the-cloud/"}
{"link": "http://techcrunch.com/2014/07/01/phonotonic-is-a-nifty-music-device-that-turns-movement-into-music/"}
{"link": "http://techcrunch.com/2014/07/01/keen-io-series-a-sequoia/"}
{"link": "http://techcrunch.com/2014/07/01/microsoft-bolsters-encryption-for-onedrive-and-outlook-com/"}
{"link": "http://techcrunch.com/2014/07/01/announcing-krakowcrunch-on-july-7/"}
{"link": "http://techcrunch.com/2014/07/01/snapup-lets-you-go-shopping-track-prices-just-by-taking-screenshots-on-your-iphone/"}
{"link": "http://techcrunch.com/2014/07/01/former-israeli-intelligence-officials-get-2-5m-to-seed-cyber-security-company-hexadite/"}
{"link": "http://techcrunch.com/2014/07/01/the-ap-is-using-robots-to-write-earnings-reports/"}
{"link": "http://techcrunch.com/2014/07/01/as-the-twitter-world-turns-anthony-noto-is-its-new-cfo-mike-gupta-now-investments-svp/"}
{"link": "http://techcrunch.com/2014/07/01/moven-series-a/"}
{"link": "http://techcrunch.com/2014/07/01/backtracker-helps-bikers-keep-from-being-rear-ended/"}
{"link": "http://techcrunch.com/2014/07/01/kinvey-mobile-identity-product-aims-to-simplify-identity-management-for-mobile-developers/"}
{"link": "http://techcrunch.com/2014/07/01/long-live-the-nav-key/"}
{"link": "http://techcrunch.com/2014/07/01/researchers-now-able-to-3d-print-working-blood-vessels/"}
{"link": "http://techcrunch.com/2014/07/01/paypal-shuts-down-secure-messaging-service-protonmails-crowdfunding-account/"}
{"link": "http://techcrunch.com/2014/07/01/art-galleries-app-artbinder-raises-3-17m-in-round-led-by-index-ventures/"}
{"link": "http://techcrunch.com/2014/07/01/uk-robotics-strategy-2020/"}
{"link": "http://techcrunch.com/2014/07/01/percentil/"}
{"link": "http://techcrunch.com/2014/07/01/super-acquisition/"}
{"link": "http://techcrunch.com/2014/07/01/relative-insight/"}
{"link": "http://techcrunch.com/2014/07/02/salesforce-mobile-reports-and-dashboards-provide-in-depth-knowledge-on-the-fly/"}
{"link": "http://techcrunch.com/2014/07/02/microsoft-goes-after-botnet-tanking-no-ips-dynamic-dns-service-for-regular-users-in-the-process/"}
{"link": "http://techcrunch.com/2014/07/02/charles-river-ventures-raises-393-million-for-its-16th-fund/"}
{"link": "http://techcrunch.com/2014/07/02/facebook-emotion-experiment/"}
{"link": "http://techcrunch.com/2014/07/02/amazon-stands-up-to-ftc-demands-for-more-parental-controls/"}
{"link": "http://techcrunch.com/2014/07/02/the-eff-sues-the-nsa-for-details-on-how-the-government-discloses-security-flaws/"}
{"link": "http://techcrunch.com/2014/07/02/stubhub-layoffs/"}
{"link": "http://techcrunch.com/2014/07/02/app-a-documentary-about-the-human-side-of-the-app-revolution/"}
{"link": "http://techcrunch.com/2014/07/02/fitmob-launches-mobtribes-gets-into-the-personal-training-market/"}
{"link": "http://techcrunch.com/2014/07/02/tetris-gets-hacked-onto-the-only-thing-its-not-already-on-a-playable-t-shirt/"}
{"link": "http://techcrunch.com/2014/07/02/microsoft-presses-ahead-with-office-for-android/"}
{"link": "http://techcrunch.com/2014/07/02/yahoo-does-a-summer-cleaning-shuts-down-its-xobni-acquisition-plus-other-under-performing-products/"}
{"link": "http://techcrunch.com/2014/07/02/former-microsoft-engineers-launch-pixotale-a-social-networking-app-for-visual-storytelling/"}
{"link": "http://techcrunch.com/2014/07/02/the-eff-calls-gov-report-supporting-surveillance-legally-flawed-and-factually-incomplete/"}
{"link": "http://techcrunch.com/2014/07/02/microsoft-acquires-syntaxtree-to-offer-better-unity-support-in-visual-studio/"}
{"link": "http://techcrunch.com/2014/07/02/facebook-liverail/"}
{"link": "http://techcrunch.com/2014/07/02/massachusetts-open-cloud-project-hopes-to-create-ad-hoc-infrastructure-marketplace/"}
{"link": "http://techcrunch.com/2014/07/02/the-satellite-is-a-science-project-to-bring-you-a-live-portrait-of-earth/"}
{"link": "http://techcrunch.com/2014/07/02/edyn-kickstarter/"}
{"link": "http://techcrunch.com/2014/07/02/scan-makes-a-qr-identity-play/"}
{"link": "http://techcrunch.com/2014/07/02/fuisz-media/"}
{"link": "http://techcrunch.com/2014/07/02/product-hunt-the-valleys-water-cooler-for-discussing-new-apps-and-services-is-coming-to-ios/"}
{"link": "http://techcrunch.com/2014/07/02/techcrunch-disrupt-europe-tour-london-prague-berlin-more/"}
{"link": "http://techcrunch.com/2014/07/02/talk-to-the-hand/"}
{"link": "http://techcrunch.com/2014/07/02/vc-tim-draper-won-the-government-bitcoin-to-bring-liquidity-to-emerging-markets/"}
{"link": "http://techcrunch.com/2014/07/02/new-picture-based-messaging-app-hipe-gives-friends-just-99-seconds-to-respond-after-reading-your-text/"}
{"link": "http://techcrunch.com/2014/07/02/coinbase-vault/"}
{"link": "http://techcrunch.com/2014/07/02/hire-someone-already-google-ventures-mulls-its-european-moves/"}
{"link": "http://techcrunch.com/2014/07/02/luminoso-lands-6-5m-in-venture-capital-to-keep-building-cloud-text-analytics-service/"}
{"link": "http://techcrunch.com/2014/07/02/ico-probes-facebook-emotion-study/"}
{"link": "http://techcrunch.com/2014/07/02/russia-moves-to-ban-online-services-that-dont-store-personal-data-in-russia/"}
{"link": "http://techcrunch.com/2014/07/02/researchers-create-walking-muscle-powered-biobots/"}
{"link": "http://techcrunch.com/2014/07/02/xiaomi-1h14-phone-sales/"}
{"link": "http://techcrunch.com/2014/07/02/us-marshals-have-sold-30000-silk-road-bitcoins/"}
{"link": "http://techcrunch.com/2014/07/02/rackspace/"}
{"link": "http://techcrunch.com/2014/07/03/go-disrupt-yourself/"}
{"link": "http://techcrunch.com/2014/07/03/homeaway-mulls-venture-fund-as-it-hits-a-milestone/"}
{"link": "http://techcrunch.com/2014/07/03/everyone-seems-mad-at-reservation-hop-founder-admits-he-was-taken-aback-by-the-criticism/"}
{"link": "http://techcrunch.com/2014/07/03/gillmor-gang-live-07-03-14/"}
{"link": "http://techcrunch.com/2014/07/03/samsung-gear-live-review-samsungs-smartwatch-first-mover-advantage-helps-its-android-wear-effort/"}
{"link": "http://techcrunch.com/2014/07/03/lg-g-watch-review-this-early-android-wear-watch-could-use-a-bit-more-time-to-bake/"}
{"link": "http://techcrunch.com/2014/07/03/facebook-events-for-you/"}
{"link": "http://techcrunch.com/2014/07/03/foundation-the-squarespace-ideation-narrative/"}
{"link": "http://techcrunch.com/2014/07/03/california-democrats-whine-over-proposed-wine-domains/"}
{"link": "http://techcrunch.com/2014/07/03/streaming-is-killing-downloads/"}
{"link": "http://techcrunch.com/2014/07/03/south-park-now-in-virtual-reality/"}
{"link": "http://techcrunch.com/2014/07/03/tandem-2014/"}
{"link": "http://techcrunch.com/2014/07/03/windows-phones-market-share-in-the-united-states-isnt-growing/"}
{"link": "http://techcrunch.com/2014/07/03/peter-thiel-is-returning-to-disrupt-sf/"}
{"link": "http://techcrunch.com/2014/07/03/bonobos-55m/"}
{"link": "http://techcrunch.com/2014/07/03/ebay-owned-e-commerce-platform-magento-shuts-down-services-aimed-at-smaller-retailers/"}
{"link": "http://techcrunch.com/2014/07/03/atlassian-expands-its-enterprise-offerings-with-jira-and-confluence-data-center/"}
{"link": "http://techcrunch.com/2014/07/03/authentication-provider-telesign-closes-round-at-49-million/"}
{"link": "http://techcrunch.com/2014/07/03/apples-hamid-mohammadinia-joins-the-vessyl-smart-cup-team/"}
{"link": "http://techcrunch.com/2014/07/03/reelagram-turns-instagram-photos-into-view-master-reels/"}
{"link": "http://techcrunch.com/2014/07/03/facebook-messenger-for-ipad/"}
{"link": "http://techcrunch.com/2014/07/03/traity/"}
{"link": "http://techcrunch.com/2014/07/03/lua-the-mobile-first-comms-tool-for-any-workforce-launches-insights-metrics-product/"}
{"link": "http://techcrunch.com/2014/07/03/how-a-former-google-data-guy-could-change-what-we-eat-for-breakfast/"}
{"link": "http://techcrunch.com/2014/07/03/android-wear-gets-its-own-companion-app-plus-a-dedicated-section-in-google-plays-app-store/"}
{"link": "http://techcrunch.com/2014/07/03/streamfully-content-previews/"}
{"link": "http://techcrunch.com/2014/07/03/can-content-pay-its-way-through-social-shares-and-tailored-email-newsletters/"}
{"link": "http://techcrunch.com/2014/07/03/citizenmes-ios-app-performs-a-personality-test-on-your-social-data/"}
{"link": "http://techcrunch.com/2014/07/04/beast-sensor-on-indiegogo-tracks-your-weight-lifting-in-real-time/"}
{"link": "http://techcrunch.com/2014/07/04/video-content-network-buzzmyvideos-launches-to-attract-international-creators/"}
{"link": "http://techcrunch.com/2014/07/04/balderton-partner-bonanzinga-steps-back-to-pursue-career-as-an-angel/"}
{"link": "http://techcrunch.com/2014/07/04/neardesk-raises-1m-on-crowd-equity-platform-seedrs/"}
{"link": "http://techcrunch.com/2014/07/04/futureperfect-ventures-is-a-small-fund-launched-to-back-applications-for-big-data/"}
{"link": "http://techcrunch.com/2014/07/04/digital-theatre/"}
{"link": "http://techcrunch.com/2014/07/04/apple-poaches-patrick-pruniaux-watch-brand-tag-heuers-vp-of-sales/"}
{"link": "http://techcrunch.com/2014/07/04/meet-the-winner-of-praguecrunch-iii-cloudfender/"}
{"link": "http://techcrunch.com/2014/07/04/just-be-present/"}
{"link": "http://techcrunch.com/2014/07/04/an-ecommerce-site-where-you-can-negotiate-the-price-you-want-to-pay/"}
{"link": "http://techcrunch.com/2014/07/04/rovio-owner-backs-teller-a-startup-aiming-to-make-email-work-better-when-you-check-it-less-often/"}
{"link": "http://techcrunch.com/2014/07/04/on-the-hunt-for-better-margins-fab-debuts-hem-a-new-furnishings-and-design-brand/"}
{"link": "http://techcrunch.com/2014/07/04/a-drone-over-praguecrunch/"}
{"link": "http://techcrunch.com/2014/07/04/the-government-once-built-silicon-valley/"}
{"link": "http://techcrunch.com/2014/07/05/lessons-from-the-sourcebits-acquisition/"}
{"link": "http://techcrunch.com/2014/07/05/israeli-high-tech-gets-aggressive/"}
{"link": "http://techcrunch.com/2014/07/05/the-new-fast-food/"}
{"link": "http://techcrunch.com/2014/07/05/zuoras-path-to-managing-the-subscription-economy/"}
{"link": "http://techcrunch.com/2014/07/05/gillmor-gang-pass-the-buck/"}
{"link": "http://techcrunch.com/2014/07/05/google-now-is-the-killer-app-for-android-wear/"}
{"link": "http://techcrunch.com/2014/07/05/mayday-campaign-finance-reform/"}
{"link": "http://techcrunch.com/2014/07/05/who-watches-the-watchmen/"}
{"link": "http://techcrunch.com/2014/07/05/hackers-target-silk-road-auction-participants-in-scam/"}
{"link": "http://techcrunch.com/2014/07/06/gartner-device-shipments-break-2-4b-units-in-2014-tablets-to-overtake-pc-sales-in-2015/"}
{"link": "http://techcrunch.com/2014/07/06/how-real-will-wearable-games-be/"}
{"link": "http://techcrunch.com/2014/07/06/cleantechs-death-has-been-greatly-exaggerated/"}
{"link": "http://techcrunch.com/2014/07/06/why-section-702-reform-matters/"}
{"link": "http://techcrunch.com/2014/07/06/charge-your-phone-before-flying-tsa-will-now-block-dead-devices-at-some-airports/"}
{"link": "http://techcrunch.com/2014/07/06/seedrs-convertible/"}
{"link": "http://techcrunch.com/2014/07/06/google-co-founders-talk-long-term-innovation-making-big-bets-and-more-in-fireside-chat-with-vinod-khosla/"}
{"link": "http://techcrunch.com/2014/07/06/wearable-solar-dress/"}
{"link": "http://techcrunch.com/2014/07/06/plug-your-phone-into-this-solar-powered-donkey/"}
{"link": "http://techcrunch.com/2014/07/06/stepup/"}
{"link": "http://techcrunch.com/2014/07/07/taylor-swift-wall-street-journal/"}
{"link": "http://techcrunch.com/2014/07/07/general-harmonics-is-basically-pied-piper-from-silicon-valley/"}
{"link": "http://techcrunch.com/2014/07/07/airbnb-showdown-on-san-franciscos-november-ballot-is-averted-for-the-time-being/"}
{"link": "http://techcrunch.com/2014/07/07/tubemogul-wants-to-go-public-for-11-13-per-share-raising-up-to-93-4m/"}
{"link": "http://techcrunch.com/topic/product/gmail/"}
{"link": "http://techcrunch.com/2014/07/07/seeing-opportunities-in-the-us-itbit-relocates-to-nyc-names-new-ceo/"}
{"link": "http://techcrunch.com/topic/product/youtube/"}
{"link": "http://techcrunch.com/2014/07/07/blackberry-explains-the-passport-its-square-tablet-phone-thing/"}
{"link": "http://techcrunch.com/2014/07/07/boxs-q1-revenue-nearly-doubles-as-its-losses-expand-a-more-modest-13/"}
{"link": "http://techcrunch.com/2014/07/07/nsa-privacy-implications/"}
{"link": "http://techcrunch.com/2014/07/07/opendoor/"}
{"link": "http://techcrunch.com/2014/07/07/bridging-the-gap-as-the-smart-home-industry-expands/"}
{"link": "http://techcrunch.com/2014/07/07/compromise-will-shape-the-wearables-market/"}
{"link": "http://techcrunch.com/2014/07/07/facebook-mobile-video/"}
{"link": "http://techcrunch.com/2014/07/07/isis-mobile-wallet-rebrands-to-distance-itself-from-militant-group-isis/"}
{"link": "http://techcrunch.com/2014/07/07/box-picks-up-150m-more-as-it-waits-for-favorable-ipo-winds/"}
{"link": "http://techcrunch.com/2014/07/07/microsoft-brings-yammer-to-more-office-365-plans-for-free/"}
{"link": "http://techcrunch.com/2014/07/07/matterport-16m-dcm/"}
{"link": "http://techcrunch.com/2014/07/07/germany-unhappy-with-u-s-over-allegations-of-a-double-agent-assisting-in-continued-spying/"}
{"link": "http://techcrunch.com/2014/07/07/mac-os-x-gets-the-dark-theme-weve-all-been-waiting-for-in-yosemite-preview-3/"}
{"link": "http://techcrunch.com/2014/07/07/blek-comes-to-android-and-i-get-stuck-on-level-23/"}
{"link": "http://techcrunch.com/2014/07/07/techcrunch-disrupt-europe-meetups-london-july-11-and-berlin-july-17/"}
{"link": "http://techcrunch.com/2014/07/07/mit-and-dropbox-alums-launch-inbox-a-next-generation-email-platform/"}
{"link": "http://techcrunch.com/2014/07/07/adtile-series-a/"}
{"link": "http://techcrunch.com/2014/07/07/robin-a-company-enabling-sensor-powered-smart-offices-raises-1-35-million/"}
{"link": "http://techcrunch.com/2014/07/07/google-street-view-cruise/"}
{"link": "http://techcrunch.com/2014/07/07/winks-connected-home-collection-arrives-at-home-depot/"}
{"link": "http://techcrunch.com/2014/07/07/talk-is-cheap/"}
{"link": "http://techcrunch.com/2014/07/07/oculus-debuts-oculus-connect-developer-conference-acquires-raknet-and-open-sources-its-tech/"}
{"link": "http://techcrunch.com/2014/07/07/lokloks-new-messaging-app-lets-you-draw-on-your-friends-lock-screen/"}
{"link": "http://techcrunch.com/2014/07/07/sigmas-50mm-f1-4-dg-hsm-art-review/"}
{"link": "http://techcrunch.com/2014/07/07/parktag-seed/"}
{"link": "http://techcrunch.com/2014/07/07/new-kinect-for-windows-now-available-for-199-shipping-july-15/"}
{"link": "http://techcrunch.com/2014/07/07/well-see-you-tonight-at-krakowcrunch/"}
{"link": "http://techcrunch.com/2014/07/07/programmer-craig-muth-kickstarts-a-new-version-of-his-arguably-amazing-shell-xiki/"}
{"link": "http://techcrunch.com/2014/07/07/virtual-reality-gets-a-real-content-studio-with-launch-of-alchemy-vr/"}
{"link": "http://techcrunch.com/2014/07/08/i-say-yo/"}
{"link": "http://techcrunch.com/2014/07/08/republicans-find-fun-new-way-for-you-to-give-them-money-gop/"}
{"link": "http://techcrunch.com/2014/07/08/microsoft-to-abandon-the-bastard-child-of-windows-phone-in-two-months/"}
{"link": "http://techcrunch.com/2014/07/08/tc-cribs-pocket-gems-where-the-office-gets-snazzed-up-100-at-a-time/"}
{"link": "http://techcrunch.com/2014/07/08/xbox-one-july-update/"}
{"link": "http://techcrunch.com/2014/07/08/amino-seed-funding/"}
{"link": "http://techcrunch.com/2014/07/08/senate-committee-advances-controversial-cybersecurity-bill/"}
{"link": "http://techcrunch.com/2014/07/08/nearly-half-the-thiel-fellows-plan-on-returning-to-school/"}
{"link": "http://techcrunch.com/2014/07/08/cartodbs-odyssey-js-is-an-open-source-tool-for-telling-stories-with-interactive-maps/"}
{"link": "http://techcrunch.com/2014/07/08/localmaven-launch/"}
{"link": "http://techcrunch.com/2014/07/08/facebook-tests-android-l-style-lock-screen-notifications/"}
{"link": "http://techcrunch.com/2014/07/08/pinterest-steps-outside-its-walled-garden-with-new-animated-follow-button-for-brands/"}
{"link": "http://techcrunch.com/2014/07/08/amazon-sends-letter-to-try-to-take-authors-out-of-the-middle-of-the-hachette-dispute/"}
{"link": "http://techcrunch.com/2014/07/08/hillary-clinton-denounces-nsa-surveillance-on-german-chancellor/"}
{"link": "http://techcrunch.com/2014/07/08/apple-brings-better-discussion-ipad-course-creation-to-itunes-u/"}
{"link": "http://techcrunch.com/2014/07/08/and-the-first-game-to-find-its-way-to-android-wear-is-yep-you-guessed-it/"}
{"link": "http://techcrunch.com/2014/07/08/curse/"}
{"link": "http://techcrunch.com/2014/07/08/apples-secret-ebay-store-returns/"}
{"link": "http://techcrunch.com/2014/07/08/uber-caps-surge-pricing-during-emergencies/"}
{"link": "http://techcrunch.com/2014/07/08/lyft-brooklyn-queens/"}
{"link": "http://techcrunch.com/2014/07/08/microsofts-project-spark-game-creation-tool-will-come-out-of-beta-in-early-october/"}
{"link": "http://techcrunch.com/2014/07/08/announcing-the-winner-of-krakowcrunch-fashionnote/"}
{"link": "http://techcrunch.com/2014/07/08/inside-boxs-updated-s-1/"}
{"link": "http://techcrunch.com/2014/07/08/googles-dart-language-is-now-an-official-ecma-standard/"}
{"link": "http://techcrunch.com/2014/07/08/planesharing/"}
{"link": "http://techcrunch.com/2014/07/08/experimenting-with-drugs-in-the-cloud/"}
{"link": "http://techcrunch.com/2014/07/08/twitter-tanks-more-than-7/"}
{"link": "http://techcrunch.com/2014/07/08/xiaomi-users-spend-more-time-in-apps-than-iphone-owners-in-china/"}
{"link": "http://techcrunch.com/2014/07/08/in-five-years-ibeaconbluetooth-low-energy-device-market-to-reach-60-million-devices/"}
{"link": "http://techcrunch.com/2014/07/08/tinder-meets-secret-meets-flirting-game-getyou-pulls-in-1-1m-seed/"}
{"link": "http://techcrunch.com/2014/07/08/ios-8-tips-apples-health-hand-with-homegrown-step-and-calorie-counting-features/"}
{"link": "http://techcrunch.com/2014/07/08/electric-objects-launches-kickstarter-campaign-to-build-displays-for-digital-art/"}
{"link": "http://techcrunch.com/2014/07/08/fly-or-die-yo/"}
{"link": "http://techcrunch.com/2014/07/08/dasher-takes-messaging-apps-up-a-notch-with-support-for-rich-content-location-sharing-gifs-and-more/"}
{"link": "http://techcrunch.com/2014/07/08/a-weekend-with-the-all-electric-bmw-i3/"}
{"link": "http://techcrunch.com/2014/07/08/linio-rocket-internet-2/"}
{"link": "http://techcrunch.com/2014/07/08/bitcoin-vault-xapo-raises-20-million-from-greylock-index-and-announces-btc-debit-cards-are-shipping-this-month/"}
{"link": "http://techcrunch.com/2014/07/08/to-drive-new-takers-for-deals-livingsocial-adds-personalized-emails-daily-gem-specials/"}
{"link": "http://techcrunch.com/2014/07/08/normal-makes-headphones-3d-printed-to-your-ear/"}
{"link": "http://techcrunch.com/2014/07/08/spark-io-raises-4-9-million-series-for-an-internet-of-things-os/"}
{"link": "http://techcrunch.com/2014/07/08/blackberry-is-one-of-the-hottest-stocks-of-2014-seriously/"}
{"link": "http://techcrunch.com/2014/07/08/apple-patents-a-way-to-make-all-glass-iphones-ipads-monitors-and-tvs/"}
{"link": "http://techcrunch.com/2014/07/08/mota-3d/"}
{"link": "http://techcrunch.com/2014/07/08/music-vault-partners-with-youtube-to-bring-13000-rare-live-music-videos-online/"}
{"link": "http://techcrunch.com/2014/07/08/retailnext-raises-another-30-million-to-track-in-store-data/"}
{"link": "http://techcrunch.com/2014/07/08/medeye-series-a/"}
{"link": "http://techcrunch.com/2014/07/08/rightster-acquires-two-more-video-companies-chad-hurley-now-advisor/"}
{"link": "http://techcrunch.com/2014/07/08/cloudian-raises-29-million-because-not-everything-needs-to-live-in-the-cloud/"}
{"link": "http://techcrunch.com/2014/07/08/fishbrain-funding/"}
{"link": "http://techcrunch.com/2014/07/09/finally-a-way-to-find-movies-worth-watching-on-netflix/"}
{"link": "http://techcrunch.com/2014/07/09/aereo-the-company-without-a-plan-b-finds-a-plan-c/"}
{"link": "http://techcrunch.com/2014/07/09/lyft-will-move-ahead-with-nyc-launch-despite-regulatory-pushback/"}
{"link": "http://techcrunch.com/2014/07/09/us-gov-declassifies-3-fisa-court-orders-commanding-the-collection-of-telephone-metadata/"}
{"link": "http://techcrunch.com/2014/07/09/hotelquickly-raises-4-5-million-to-double-down-on-last-minute-hotel-booking-in-asia-pacific/"}
{"link": "http://techcrunch.com/2014/07/09/fuel-cell-cars-are-going-to-get-a-big-boost-in-california-next-year/"}
{"link": "http://techcrunch.com/2014/07/09/mnectar/"}
{"link": "http://techcrunch.com/2014/07/09/twitterball/"}
{"link": "http://techcrunch.com/2014/07/09/forget-ok-glass-mindrdr-is-a-new-google-glass-app-that-you-control-with-your-thoughts/"}
{"link": "http://techcrunch.com/2014/07/09/yelp-google-anti-trust/"}
{"link": "http://techcrunch.com/2014/07/09/bitcoin-foundation-hires-lobbying-group-to-take-the-cryptocurrency-to-washington/"}
{"link": "http://techcrunch.com/2014/07/09/connected-tv-market-crosses-1b-devices-as-google-pins-its-hopes-on-android-tv/"}
{"link": "http://techcrunch.com/2014/07/09/homestar-runner-will-return/"}
{"link": "http://techcrunch.com/2014/07/09/american-surveillance-victim-is-not-surprised-the-nsa-was-spying/"}
{"link": "http://techcrunch.com/2014/07/09/regina-dugan-joins-zynga-board/"}
{"link": "http://techcrunch.com/2014/07/09/tinders-sean-rad/"}
{"link": "http://techcrunch.com/2014/07/09/privacy-and-religious-groups-condemn-nsa-surveillance-of-muslim-americans/"}
{"link": "http://techcrunch.com/2014/07/09/ultratext-is-a-simple-gif-making-app-that-works-with-imessage/"}
{"link": "http://techcrunch.com/2014/07/09/android-wear-needs-to-be-more-thoughtful-about-bugging-you/"}
{"link": "http://techcrunch.com/2014/07/09/paypal-makes-good-on-its-braintree-acquisition-with-launch-of-new-developer-tools-the-braintree-v-zero-sdk/"}
{"link": "http://techcrunch.com/2014/07/09/tribune-whats-on/"}
{"link": "http://techcrunch.com/2014/07/09/whitney-wolfe-vs-tinder/"}
{"link": "http://techcrunch.com/2014/07/09/microsoft-tweaks-office-365-for-smaller-businesses/"}
{"link": "http://techcrunch.com/2014/07/09/digitalocean-closes-10m-equipment-lease-from-capx-partners/"}
{"link": "http://techcrunch.com/2014/07/09/fates-forever/"}
{"link": "http://techcrunch.com/2014/07/09/polymos-new-iphone-app-helps-you-pre-organize-your-photos/"}
{"link": "http://techcrunch.com/2014/07/09/microsoft-updates-azure-with-2-new-u-s-regions-improved-hybrid-storage-solution-and-more/"}
{"link": "http://techcrunch.com/2014/07/09/google-adds-android-smartphone-and-tablet-screen-mirroring-to-chromecast/"}
{"link": "http://techcrunch.com/2014/07/09/adheretech-raises-1-75-million-in-series-a/"}
{"link": "http://techcrunch.com/2014/07/09/expect-labs-releases-api-for-better-voice-controls-and-content-discovery/"}
{"link": "http://techcrunch.com/2014/07/09/the-lte-verision-of-sonys-ultra-slim-xperia-z2-tablet-hits-verizon-exclusively/"}
{"link": "http://techcrunch.com/2014/07/09/nsa-and-fbi-spied-on-muslim-american-leaders/"}
{"link": "http://techcrunch.com/2014/07/09/samsungs-race-to-the-bottom/"}
{"link": "http://techcrunch.com/2014/07/09/sprint-asks-if-two-useless-things-can-become-one-useful-one-with-the-livepro-projector-hotspot/"}
{"link": "http://techcrunch.com/2014/07/09/chinese-supercloner-xiaomi-expected-to-release-a-fitness-tracker/"}
{"link": "http://techcrunch.com/2014/07/09/google-maps-update-lets-you-measure-distance-draw-crude-pictures/"}
{"link": "http://techcrunch.com/2014/07/09/uk-widens-ban-on-dead-mobile-devices-on-flights/"}
{"link": "http://techcrunch.com/2014/07/09/urban-airship-ceo-steps-down-amid-sexual-assault-allegations/"}
{"link": "http://techcrunch.com/2014/07/09/germanys-stunning-world-cup-win-over-brazil-is-the-most-tweeted-sports-game-ever/"}
{"link": "http://techcrunch.com/2014/07/09/craftbot3d/"}
{"link": "http://techcrunch.com/2014/07/09/david-tischs-stealthy-mobile-commerce-product-spring-closes-7-5m-series-a/"}
{"link": "http://techcrunch.com/2014/07/09/diy-website-builder-wix-gets-into-email-newsletters/"}
{"link": "http://techcrunch.com/2014/07/09/original-google-glass-chief-gives-us-a-clue-about-googles-prime-motivator-in-wearable-design/"}
{"link": "http://techcrunch.com/2014/07/09/137-ventures-fund-ii/"}
{"link": "http://techcrunch.com/2014/07/09/yelp-versus-google/"}
{"link": "http://techcrunch.com/2014/07/09/zynstra-seriesb/"}
{"link": "http://techcrunch.com/2014/07/09/13-european-student-run-startups-get-100k-each-from-founder-org/"}
{"link": "http://techcrunch.com/2014/07/09/busbud-series-a/"}
{"link": "http://techcrunch.com/2014/07/09/credit-benchmark-series-a/"}
{"link": "http://techcrunch.com/2014/07/09/duetto/"}
{"link": "http://techcrunch.com/2014/07/09/rackware-raises-2-3m-for-its-cloud-management-solution/"}
{"link": "http://techcrunch.com/2014/07/09/clime-sensors-are-tiny-tags-that-tell-you-when-things-are-heating-up/"}
{"link": "http://techcrunch.com/2014/07/09/bcc-fail-by-no-10-downing-st-accidentally-creates-brand-new-startup-groups/"}
{"link": "http://techcrunch.com/2014/07/09/gunmaker-skirts-laws-by-3d-printing-a-single-firearm-part/"}
{"link": "http://techcrunch.com/2014/07/09/newvoicemedia-raises-another-50m-for-its-cloud-based-contact-centers/"}
{"link": "http://techcrunch.com/2014/07/09/watch-this-beautiful-3d-printed-tourbillon-in-action/"}
{"link": "http://techcrunch.com/2014/07/09/format-acquires-format-com-updates-its-portfolio-website-app-as-it-relaunches/"}
{"link": "http://techcrunch.com/2014/07/10/silicon-valleys-real-estate-crunch-is-a-golden-opportunity-for-other-american-cities/"}
{"link": "http://techcrunch.com/2014/07/10/disrupt-with-care/"}
{"link": "http://techcrunch.com/2014/07/10/amazon-asks-faa-for-permission-to-test-its-delivery-drones/"}
{"link": "http://techcrunch.com/2014/07/10/dash-hudson-seed-funding/"}
{"link": "http://techcrunch.com/2014/07/10/rent-a-bike-near-you-at-the-touch-of-a-button/"}
{"link": "http://techcrunch.com/2014/07/10/d-wave-systems-raises-28-4-million-round/"}
{"link": "http://techcrunch.com/2014/07/10/cell-phone-unlocking-bill-clears-senate-committee/"}
{"link": "http://techcrunch.com/2014/07/10/parking-up-the-wrong-tree/"}
{"link": "http://techcrunch.com/2014/07/10/out-app-purchases/"}
{"link": "http://techcrunch.com/2014/07/10/our-polyglot-nightmare/"}
{"link": "http://techcrunch.com/2014/07/10/satya-nadellas-vision-for-a-new-microsoft/"}
{"link": "http://techcrunch.com/2014/07/10/after-7-years-of-searching-halo-3s-last-easter-egg-has-been-found/"}
{"link": "http://techcrunch.com/2014/07/10/microsoft-closer-to-removing-european-right-to-be-forgotten-requests/"}
{"link": "http://techcrunch.com/2014/07/10/apples-living-library/"}
{"link": "http://techcrunch.com/2014/07/10/elon-musk-donates-1-million-to-the-oatmeals-nikola-tesla-museum/"}
{"link": "http://techcrunch.com/2014/07/10/ftc-takes-legal-action-against-amazon-for-unauthorized-in-app-purchases/"}
{"link": "http://techcrunch.com/2014/07/10/online-clothing-resale-store-twice-rolls-out-same-day-pickup-with-twice-local/"}
{"link": "http://techcrunch.com/2014/07/10/mlbs-ibeacon-project-enters-phase-two-with-interactive-ballpark-attractions/"}
{"link": "http://techcrunch.com/2014/07/10/misfit-moves-further-away-from-hardware-and-into-platform-territory-with-new-beddit-integration/"}
{"link": "http://techcrunch.com/2014/07/10/google-microsoft-ibm-and-others-collaborate-to-make-managing-docker-containers-easier/"}
{"link": "http://techcrunch.com/2014/07/10/cover-5-5m-spark/"}
{"link": "http://techcrunch.com/2014/07/10/tech-company-with-39-in-assets-now-worth-more-than-6b/"}
{"link": "http://techcrunch.com/2014/07/10/the-app-store-six-years-later/"}
{"link": "http://techcrunch.com/2014/07/10/this-humanoid-robot-uses-walking-sticks-to-climb-over-rubble/"}
{"link": "http://techcrunch.com/2014/07/10/publishing-start-up-tablo-raises-400000-seed-round/"}
{"link": "http://techcrunch.com/2014/07/10/vaavud-takes-to-kickstarter-again-for-a-new-smartphone-wind-meter-that-tracks-direction/"}
{"link": "http://techcrunch.com/2014/07/10/amazon-goes-after-box-dropbox-and-huddle-launches-zocalo-for-secure-enterprise-storage/"}
{"link": "http://techcrunch.com/2014/07/10/button/"}
{"link": "http://techcrunch.com/2014/07/10/microsoft-still-not-selling-xbox/"}
{"link": "http://techcrunch.com/2014/07/10/postup/"}
{"link": "http://techcrunch.com/2014/07/10/godaddy-acqui-hires-founders-of-smart-calendaring-app-canary/"}
{"link": "http://techcrunch.com/2014/07/10/soundcloud-lands-on-sonos/"}
{"link": "http://techcrunch.com/2014/07/10/microsoft-ceo-gears-the-company-for-change-and-a-renewed-focus-on-productivity-and-platforms/"}
{"link": "http://techcrunch.com/2014/07/10/linkedin-steps-up-its-ai-play-turns-its-contacts-app-into-a-new-connected-app/"}
{"link": "http://techcrunch.com/2014/07/10/jobandtalent-series-a/"}
{"link": "http://techcrunch.com/2014/07/10/kent-goldman-upside-partnership/"}
{"link": "http://techcrunch.com/2014/07/10/code-for-america-announces-five-companies-for-accelerator-program/"}
{"link": "http://techcrunch.com/2014/07/10/freedompop-brings-its-free-wireless-service-to-europe-sans-handsets/"}
{"link": "http://techcrunch.com/2014/07/10/uk-fast-tracks-emergency-surveillance-law/"}
{"link": "http://techcrunch.com/2014/07/10/taskrabbit-debuts-revamped-platform-launches-new-website-and-mobile-apps/"}
{"link": "http://techcrunch.com/2014/07/10/applet-patents-stronger-sapphire-displays-and-illuminated-sapphire-controls/"}
{"link": "http://techcrunch.com/2014/07/10/getty-images-and-istock-ios-apps-get-a-big-overhaul-and-the-new-embed-function/"}
{"link": "http://techcrunch.com/2014/07/10/google-ventures-in-europe-and-the-missing-fifth-man/"}
{"link": "http://techcrunch.com/2014/07/10/google-ventures-london/"}
{"link": "http://techcrunch.com/2014/07/11/647000-comments-have-been-sent-to-the-fcc-about-net-neutrality-keep-them-coming/"}
{"link": "http://techcrunch.com/2014/07/11/what-should-ycs-sam-altman-do-with-these-bizarre-conway-paul-graham-oil-paintings/"}
{"link": "http://techcrunch.com/2014/07/11/lyft-will-not-launch-in-new-york-today-company-says-it-will-work-with-taxi-commission/"}
{"link": "http://techcrunch.com/2014/07/11/lastpass-finds-security-holes-in-its-online-password-manager-doesnt-think-anyone-exploited-them/"}
{"link": "http://techcrunch.com/2014/07/11/landscape-mobile-launches-sight-raises-seed-round-to-visually-archive-articles/"}
{"link": "http://techcrunch.com/2014/07/11/instagram-direct/"}
{"link": "http://techcrunch.com/2014/07/11/crooks-reainmate-a-dead-botnet-to-target-high-value-bank-accounts/"}
{"link": "http://techcrunch.com/2014/07/11/apple-spent-over-3b-with-7000-u-s-small-businesses-in-2013/"}
{"link": "http://techcrunch.com/2014/07/11/crunchweek-the-latest-tinder-drama-the-new-new-microsoft-lyfts-struggles-to-launch-in-nyc/"}
{"link": "http://techcrunch.com/2014/07/11/investments-in-the-uk-surge-to-nearly-1b-as-london-is-calling/"}
{"link": "http://techcrunch.com/2014/07/11/just-genius/"}
{"link": "http://techcrunch.com/2014/07/11/yahoo-acquires-video-streaming-platform-rayv/"}
{"link": "http://techcrunch.com/2014/07/11/this-week-on-the-tc-gadgets-podcast-misfit-android-wear-and-samsung-earnings/"}
{"link": "http://techcrunch.com/2014/07/11/apple-opens-up-with-a-new-blog-about-swift-its-new-programming-language/"}
{"link": "http://techcrunch.com/2014/07/11/xkit-the-tumblr-client-for-power-users-arrives-on-ios/"}
{"link": "http://techcrunch.com/2014/07/11/twitter-analytics-dashboard/"}
{"link": "http://techcrunch.com/2014/07/11/fcc-approves-billions-to-bring-wi-fi-to-more-american-schools/"}
{"link": "http://techcrunch.com/2014/07/11/developer-predicted-lebrons-move-to-the-cavs-with-website-analysis/"}
{"link": "http://techcrunch.com/2014/07/11/microsoft-acquires-disaster-recovery-service-inmage/"}
{"link": "http://techcrunch.com/2014/07/11/chinese-state-media-renews-anti-apple-rhetoric-calls-the-iphone-a-national-security-concern/"}
{"link": "http://techcrunch.com/2014/07/11/the-pc-market-has-its-strongest-quarter-in-recent-memory/"}
{"link": "http://techcrunch.com/2014/07/11/loverly-gets-editorial-with-launch-of-new-content-hub/"}
{"link": "http://techcrunch.com/2014/07/11/young-ponomusic/"}
{"link": "http://techcrunch.com/2014/07/11/digg-relaunches-news-me-as-a-personalized-news-alerting-service-digg-deeper/"}
{"link": "http://techcrunch.com/2014/07/11/salesforce-buys-big-data-startup-relateiq-for-up-to-390m/"}
{"link": "http://techcrunch.com/2014/07/11/science-inc-acquires-armenian-mobile-app-maker-inlight/"}
{"link": "http://techcrunch.com/2014/07/11/amplitude-the-analytics-startup-undercutting-mixpanel-raises-2-million-seed-round/"}
{"link": "http://techcrunch.com/2014/07/11/mit-researchers-build-drones-that-automatically-provide-picture-perfect-lighting-for-photographers/"}
{"link": "http://techcrunch.com/2014/07/11/barkbox-series-b/"}
{"link": "http://techcrunch.com/2014/07/11/kids-can-now-teach-robots-to-play-angry-birds-for-science/"}
{"link": "http://techcrunch.com/2014/07/11/techcrunch-giveaway-three-lg-g3-phones-g3g3g3/"}
{"link": "http://techcrunch.com/2014/07/11/the-orange-maker-spins-the-plate-to-make-better-3d-prints/"}
{"link": "http://techcrunch.com/2014/07/11/mind-candy-acton-smith/"}
{"link": "http://techcrunch.com/2014/07/11/google-agitates-for-public-debate-on-europes-right-to-be-forgotten-ruling/"}
{"link": "http://techcrunch.com/2014/07/12/software-entrepreneurs-must-go-mobile-first-or-die/"}
{"link": "http://techcrunch.com/2014/07/12/looking-for-a-niche-cheap-hotel-try-the-poshpacker/"}
{"link": "http://techcrunch.com/2014/07/12/money-at-our-fingertips/"}
{"link": "http://techcrunch.com/2014/07/12/caviar-square/"}
{"link": "http://techcrunch.com/2014/07/12/humans-and-computers-will-come-together-for-middle-work/"}
{"link": "http://techcrunch.com/2014/07/12/hardware-is-the-new-software/"}
{"link": "http://techcrunch.com/2014/07/12/gillmor-gang-taming-of-the-stream/"}
{"link": "http://techcrunch.com/2014/07/12/amazon-web-services-moves-beyond-developer-tools/"}
{"link": "http://techcrunch.com/2014/07/12/the-great-fragmentation-we-are-all-weirdos-now/"}
{"link": "http://techcrunch.com/2014/07/13/screenshot-claims-to-show-off-the-coming-windows-8-1-start-menu/"}
{"link": "http://techcrunch.com/2014/07/13/publicize-startup-pr/"}
{"link": "http://techcrunch.com/2014/07/13/winners-of-the-techcrunch-london-meetup-giftgaming-rook-and-keekla/"}
{"link": "http://techcrunch.com/2014/07/13/snapchat-riolive2014/"}
{"link": "http://techcrunch.com/2014/07/13/silicon-valleys-dilemma-over-credentials/"}
{"link": "http://techcrunch.com/2014/07/13/hfc-academy/"}
{"link": "http://techcrunch.com/2014/07/13/german-cartel-office-says-google-other-tech-giants-could-be-regulated-like-utilities-report/"}
{"link": "http://techcrunch.com/2014/07/13/1025132/"}
{"link": "http://techcrunch.com/2014/07/14/mary-elizabeth-phillips/"}
{"link": "http://techcrunch.com/2014/07/14/snowden-document-exposes-extensive-list-of-british-spying-tools/"}
{"link": "http://techcrunch.com/2014/07/14/oculus-spots-people-selling-rift-pre-orders-cancels-their-shipments/"}
{"link": "http://techcrunch.com/2014/07/14/fly-or-die-adobe-ink-slide/"}
{"link": "http://techcrunch.com/2014/07/14/autobutler-raises-e5-8m-to-vet-garages-for-european-car-owners/"}
{"link": "http://techcrunch.com/2014/07/14/lexalytics-acquires-semantria-to-bring-sentiment-analysis-to-the-masses/"}
{"link": "http://techcrunch.com/2014/07/14/y-combinator-calls-for-strict-net-neutrality-rules-reclassification-of-broadband-under-title-ii/"}
{"link": "http://techcrunch.com/2014/07/14/do-you-feel-pressure-or-do-you-apply-pressure/"}
{"link": "http://techcrunch.com/2014/07/14/squink-lets-you-print-a-circuit-board-for-the-price-of-a-cup-of-coffee/"}
{"link": "http://techcrunch.com/2014/07/14/love-virtually-no-sex/"}
{"link": "http://techcrunch.com/2014/07/14/real-cheese-from-a-lab-no-cow-necessary/"}
{"link": "http://techcrunch.com/2014/07/14/toonimo-raises-2-5m-to-liven-up-websites-with-custom-cartoons/"}
{"link": "http://techcrunch.com/2014/07/14/scribblelive-acquires-coveritlive-will-still-operate-both-brands/"}
{"link": "http://techcrunch.com/2014/07/14/floret-is-a-gamified-dating-app-for-virtual-romance/"}
{"link": "http://techcrunch.com/2014/07/14/google-other-leading-internet-companies-support-net-neutrality-call-for-extension-to-mobile-providers/"}
{"link": "http://techcrunch.com/2014/07/14/please-dont-spam-us/"}
{"link": "http://techcrunch.com/2014/07/14/please-join-us-for-the-9th-annual-august-capital-party-in-silicon-valley/"}
{"link": "http://techcrunch.com/2014/07/14/microsoft-presses-ahead-with-its-cloud-strategy/"}
{"link": "http://techcrunch.com/2014/07/14/anonymish-app-secret-has-raised-another-25m-adds-facebook-login-and-collections/"}
{"link": "http://techcrunch.com/2014/07/14/timberman-is-the-new-flappy-bird/"}
{"link": "http://techcrunch.com/2014/07/14/google-brings-ingress-location-based-game-to-iphone-and-ipad/"}
{"link": "http://techcrunch.com/2014/07/14/srpago/"}
{"link": "http://techcrunch.com/2014/07/14/wiper-launches-its-secure-messaging-app-with-2-5-million-in-seed-funding/"}
{"link": "http://techcrunch.com/2014/07/14/the-lifetip-doesnt-need-to-touch-you-to-know-your-heart/"}
{"link": "http://techcrunch.com/2014/07/14/researchers-create-a-flying-drone-that-can-light-your-snapshots/"}
{"link": "http://techcrunch.com/2014/07/14/upside-raises-1-1m-to-help-investment-advisers-compete-against-wealthfront-betterment-and-co/"}
{"link": "http://techcrunch.com/2014/07/14/mit-is-working-on-t-1000-style-state-shifting-robots-with-googles-robot-company/"}
{"link": "http://techcrunch.com/2014/07/14/google-glass-creator-heads-to-amazon/"}
{"link": "http://techcrunch.com/2014/07/14/crv-16th-fund/"}
{"link": "http://techcrunch.com/2014/07/14/makerbot-comes-to-select-home-depot-stores/"}
{"link": "http://techcrunch.com/2014/07/14/linkedin-acquires-newsle-to-deliver-more-relevant-news-about-your-connections/"}
{"link": "http://techcrunch.com/2014/07/14/beer-the-best-use-of-crowdfunding-or-the-most-best-use-of-crowdfunding/"}
{"link": "http://techcrunch.com/2014/07/14/googles-leaked-play-store-redesign-foregrounds-media-and-summaries/"}
{"link": "http://techcrunch.com/2014/07/14/rocketrip-the-company-that-pays-you-to-save-money-on-business-trips-raises-3-million/"}
{"link": "http://techcrunch.com/2014/07/14/comcast-skydog/"}
{"link": "http://techcrunch.com/2014/07/14/apple-asserts-its-commitment-to-privacy-in-response-to-report-by-chinas-cctv/"}
{"link": "http://techcrunch.com/2014/07/14/ashton-kutcher-touts-taptalk-to-his-16m-twitter-fans/"}
{"link": "http://techcrunch.com/2014/07/14/bitcoin-mining-company-buys-critical-site-to-improve-google-results/"}
{"link": "http://techcrunch.com/2014/07/14/raspberry-pi-model-b-plus/"}
{"link": "http://techcrunch.com/2014/07/14/unboxing-echobox/"}
